name: Build & Push Docker Image

on:
  push:
    branches: [ "custom-ui" ]        # اگر بعداً از custom-ui می‌سازی، اینو بکن "custom-ui"
  workflow_dispatch: {}          # اجرا دستی از تب Actions

concurrency:
  group: docker-build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write            # برای push به GHCR با GITHUB_TOKEN

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository_owner }}/glgopen-webui
          tags: |
            type=raw,value=custom-ui
            type=sha,format=short,prefix=custom-ui-,suffix=
          labels: |
            org.opencontainers.image.source=${{ github.repository }}

      - name: Build and Push
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
